import type { Vehicle } from '../../domain/models'

// Identities and fleet states transcribed from Figma node 74:1309.
// Capacity and coordinates are demo assumptions, not live telemetry.
export const sourceFleet: Vehicle[] = [
  {
    id: 'VEH055',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Peliyagoda',
    lat: 6.94,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH027',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kaduwela',
    lat: 6.958,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH023',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 06',
    lat: 6.976,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH001',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'En route to OUT057 \u00b7 3s ago',
    lat: 6.994000000000001,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH087',
    brand: 'Tech',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Offline',
    location: 'Negombo',
    lat: 7.0120000000000005,
    lng: 79.948,
    updatedMinutes: 6,
  },
  {
    id: 'VEH042',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Gampaha',
    lat: 7.03,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH002',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.048,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH003',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.066000000000001,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH004',
    brand: 'Fresh',
    type: 'Truck',
    reefer: true,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.0840000000000005,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH005',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.102,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH006',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 6.94,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH007',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 6.958,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH008',
    brand: 'Style',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 6.976,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH009',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 6.994000000000001,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH010',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.0120000000000005,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH011',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.03,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH012',
    brand: 'Tech',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.048,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH013',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.066000000000001,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH014',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Available',
    location: 'Peliyagoda depot',
    lat: 7.0840000000000005,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH015',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 04',
    lat: 7.102,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH016',
    brand: 'Fresh',
    type: 'Truck',
    reefer: true,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 05',
    lat: 6.94,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH017',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 06',
    lat: 6.958,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH018',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 01',
    lat: 6.976,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH019',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 02',
    lat: 6.994000000000001,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH020',
    brand: 'Style',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 03',
    lat: 7.0120000000000005,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH021',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 04',
    lat: 7.03,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH022',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 05',
    lat: 7.048,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH024',
    brand: 'Tech',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'Loading',
    location: 'Peliyagoda \u00b7 Bay 01',
    lat: 7.066000000000001,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH025',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Colombo',
    lat: 7.0840000000000005,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH026',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Gampaha',
    lat: 7.102,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH028',
    brand: 'Fresh',
    type: 'Truck',
    reefer: true,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Negombo',
    lat: 6.94,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH029',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Wattala',
    lat: 6.958,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH030',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Peliyagoda',
    lat: 6.976,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH031',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kandy',
    lat: 6.994000000000001,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH032',
    brand: 'Style',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Kelaniya',
    lat: 7.0120000000000005,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH033',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Colombo',
    lat: 7.03,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH034',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Gampaha',
    lat: 7.048,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH035',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kaduwela',
    lat: 7.066000000000001,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH036',
    brand: 'Tech',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Negombo',
    lat: 7.0840000000000005,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH037',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Wattala',
    lat: 7.102,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH038',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Peliyagoda',
    lat: 6.94,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH039',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kandy',
    lat: 6.958,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH040',
    brand: 'Fresh',
    type: 'Truck',
    reefer: true,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Kelaniya',
    lat: 6.976,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH041',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Colombo',
    lat: 6.994000000000001,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH043',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kaduwela',
    lat: 7.0120000000000005,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH044',
    brand: 'Style',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Negombo',
    lat: 7.03,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH045',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Wattala',
    lat: 7.048,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH046',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Peliyagoda',
    lat: 7.066000000000001,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH047',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kandy',
    lat: 7.0840000000000005,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH048',
    brand: 'Tech',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Kelaniya',
    lat: 7.102,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH049',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Colombo',
    lat: 6.94,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH050',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Gampaha',
    lat: 6.958,
    lng: 79.926,
    updatedMinutes: 0,
  },
  {
    id: 'VEH051',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Kaduwela',
    lat: 6.976,
    lng: 79.948,
    updatedMinutes: 0,
  },
  {
    id: 'VEH052',
    brand: 'Fresh',
    type: 'Truck',
    reefer: true,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Negombo',
    lat: 6.994000000000001,
    lng: 79.97,
    updatedMinutes: 0,
  },
  {
    id: 'VEH053',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Wattala',
    lat: 7.0120000000000005,
    lng: 79.86,
    updatedMinutes: 0,
  },
  {
    id: 'VEH054',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'En route',
    location: 'Peliyagoda',
    lat: 7.03,
    lng: 79.882,
    updatedMinutes: 0,
  },
  {
    id: 'VEH056',
    brand: 'Style',
    type: 'Truck',
    reefer: false,
    weightCapacity: 2400,
    volumeCapacity: 12,
    status: 'En route',
    location: 'Kelaniya',
    lat: 7.048,
    lng: 79.904,
    updatedMinutes: 0,
  },
  {
    id: 'VEH057',
    brand: 'Tech',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Offline',
    location: 'Colombo',
    lat: 7.066000000000001,
    lng: 79.926,
    updatedMinutes: 4,
  },
  {
    id: 'VEH058',
    brand: 'Fresh',
    type: 'Van',
    reefer: true,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Offline',
    location: 'Gampaha',
    lat: 7.0840000000000005,
    lng: 79.948,
    updatedMinutes: 5,
  },
  {
    id: 'VEH059',
    brand: 'Style',
    type: 'Van',
    reefer: false,
    weightCapacity: 800,
    volumeCapacity: 4,
    status: 'Offline',
    location: 'Kaduwela',
    lat: 7.102,
    lng: 79.97,
    updatedMinutes: 6,
  },
]
