import type { TeamMember } from '../../domain/models'

/** The six identities actually shown in Figma; remaining source totals are aggregates. */
export const sourceTeam: TeamMember[] = [
  {
    id: 'USR001',
    name: 'Sanjeewa Bandara',
    email: 'sanjeewa@example.test',
    mobile: '+94 76 330 9187',
    role: 'driver',
    depot: 'Peliyagoda',
    assignment: 'VEH055 · Trip 1',
    vehicleId: 'VEH055',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
  },
  {
    id: 'USR002',
    name: 'Kasun Fernando',
    email: 'kasun@example.test',
    mobile: '+94 77 210 4455',
    role: 'dispatcher',
    depot: 'Peliyagoda',
    assignment: 'Planning office',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
  },
  {
    id: 'USR003',
    name: 'Ruwan Silva',
    email: 'ruwan@example.test',
    mobile: '+94 71 884 2210',
    role: 'loader',
    depot: 'Peliyagoda',
    assignment: 'Dock bay 03',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
  },
  {
    id: 'USR004',
    name: 'Nimal Perera',
    email: 'nimal@example.test',
    mobile: '+94 75 602 1934',
    role: 'store-manager',
    depot: 'Peliyagoda',
    assignment: 'OUT001 · Fresh',
    outletId: 'OUT001',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
  },
  {
    id: 'USR005',
    name: 'Chamari Wijesinghe',
    email: 'chamari@example.test',
    mobile: '+94 77 123 4567',
    role: 'driver',
    depot: 'Kandy',
    assignment: 'VEH012',
    vehicleId: 'VEH012',
    status: 'Invited',
    onRoute: false,
    accessState: 'Invitation pending',
  },
  {
    id: 'USR006',
    name: 'Ishara Gunawardena',
    email: 'ishara@example.test',
    mobile: '+94 70 448 7720',
    role: 'store-manager',
    depot: 'Peliyagoda',
    assignment: 'OUT014 · Style',
    outletId: 'OUT014',
    status: 'Suspended',
    onRoute: false,
    accessState: 'Ready',
  },
]
export const unlistedTeamCounts = { Active: 37, Invited: 4, Suspended: 1 }
