import type { MemberActivity, TeamMember } from '../../domain/models'

/** The six identities actually shown in Figma; remaining source totals are aggregates. */
export const sourceTeam: TeamMember[] = [
  {
    id: 'USR001',
    name: 'Sanjeewa Bandara',
    email: 'sanjeewa@example.test',
    mobile: '+94 76 330 9187',
    role: 'driver',
    depot: 'Peliyagoda',
    assignment: 'VEH055 · Trip 1',
    vehicleId: 'VEH055',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
    username: 'sanjeewa.bandara',
    lastActive: 'On route',
    joined: '24 September',
    lastSeen: '05:44 · near Peliyagoda',
  },
  {
    id: 'USR002',
    name: 'Kasun Fernando',
    email: 'kasun@example.test',
    mobile: '+94 77 210 4455',
    role: 'dispatcher',
    depot: 'Peliyagoda',
    assignment: 'Planning office',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
    username: 'kasun.fernando',
    lastActive: 'Just now',
    joined: '12 September',
    lastSeen: 'Just now',
  },
  {
    id: 'USR003',
    name: 'Ruwan Silva',
    email: 'ruwan@example.test',
    mobile: '+94 71 884 2210',
    role: 'loader',
    depot: 'Peliyagoda',
    assignment: 'Dock bay 03',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
    username: 'ruwan.silva',
    lastActive: '05:10',
    joined: '12 September',
    lastSeen: '05:10 · Dock bay 03',
  },
  {
    id: 'USR004',
    name: 'Nimal Perera',
    email: 'nimal@example.test',
    mobile: '+94 75 602 1934',
    role: 'store-manager',
    depot: 'Peliyagoda',
    assignment: 'OUT001 · Fresh',
    outletId: 'OUT001',
    status: 'Active',
    onRoute: false,
    accessState: 'Ready',
    username: 'nimal.perera',
    lastActive: '05:41',
    joined: '14 September',
    lastSeen: '05:41 · OUT001',
  },
  {
    id: 'USR005',
    name: 'Chamari Wijesinghe',
    email: 'chamari@example.test',
    mobile: '+94 77 123 4567',
    role: 'driver',
    depot: 'Kandy',
    assignment: 'VEH012',
    vehicleId: 'VEH012',
    status: 'Invited',
    onRoute: false,
    accessState: 'Invitation pending',
    username: 'chamari.wijesinghe',
    lastActive: 'Not signed in',
  },
  {
    id: 'USR006',
    name: 'Ishara Gunawardena',
    email: 'ishara@example.test',
    mobile: '+94 70 448 7720',
    role: 'store-manager',
    depot: 'Peliyagoda',
    assignment: 'OUT014 · Style',
    outletId: 'OUT014',
    status: 'Suspended',
    onRoute: false,
    accessState: 'Ready',
    username: 'ishara.gunawardena',
    lastActive: '3 days ago',
    joined: '2 September',
    lastSeen: '3 days ago',
  },
]
export const unlistedTeamCounts = { Active: 37, Invited: 4, Suspended: 1 }

/** What the Figma user detail shows for the driver; other people show their audit entries only. */
export const memberActivityReference: Record<string, MemberActivity[]> = {
  USR001: [
    { when: '05:41', title: 'Submitted delivery proof', detail: 'ORD1042 · OUT001' },
    { when: '05:36', title: 'Went offline', detail: 'Kandy corridor, no signal' },
    { when: '05:02', title: 'Started Trip 1', detail: 'VEH055 · 2 stops' },
    { when: '04:58', title: 'Signed in', detail: 'Phone browser' },
    { when: '24 Sep', title: 'Role assigned', detail: 'By Administrator · Driver' },
  ],
}
